'''
You are given two strings s and t.

String t is generated by random shuffling string s 
and then add one more letter at a random position.

Return the letter that was added to t.
'''

'''
Note:
Use XOR operator to compare two inputs
Convert two inputs into two ASCII code and use XOR operator to XOR every element from both inputs together
Similar elements will be removed from the result except the only different element

'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0
        for ch in s:
            result ^= ord(ch)
        for ch in t:
            result ^= ord(ch)
        return chr(result)

if __name__ == "__main__":
    solution = Solution()
    s = "abcd"
    t = "edcba"
    check = solution.findTheDifference(s,t)
    print(check)